/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
public class apuesta_form extends javax.swing.JFrame {

    /**
     * Creates new form apuesta_form
     */
    public apuesta_form() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setResizable(false);

        txt_saldo_t.setText("0");
        txt_v_apuesta.setText("0");
        
        double randomNum = 1/(Math.random()*2);
        BigDecimal randomm = new BigDecimal(randomNum).setScale(2, RoundingMode.HALF_UP);
        double rand1 = randomm.doubleValue();
        
        btn_nacional.setText(String.valueOf(rand1));
        double randomNum_dos = 1/(Math.random()*2);
        BigDecimal random = new BigDecimal(randomNum_dos).setScale(2, RoundingMode.HALF_UP);
        double rand2 = random.doubleValue();
      
        if(randomNum_dos==randomNum){
        randomNum_dos = 1/(Math.random()*2);
        random = new BigDecimal(randomNum_dos).setScale(2, RoundingMode.HALF_UP);
        rand2 = random.doubleValue();
           
           btn_catolica.setText(String.valueOf(rand2));
        }else{
         btn_catolica.setText(String.valueOf(rand2));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        txt_saldo_t = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_nacional = new javax.swing.JButton();
        btn_catolica = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_v_apuesta = new javax.swing.JTextField();
        txt_pago = new javax.swing.JTextField();
        btn_apostar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fondo_dos = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(null);

        txt_saldo_t.setEditable(false);
        txt_saldo_t.setBackground(new java.awt.Color(0, 0, 0));
        txt_saldo_t.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txt_saldo_t.setForeground(new java.awt.Color(255, 255, 255));
        txt_saldo_t.setBorder(null);
        txt_saldo_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saldo_tActionPerformed(evt);
            }
        });
        panel1.add(txt_saldo_t);
        txt_saldo_t.setBounds(370, 20, 170, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saldo total:");
        panel1.add(jLabel1);
        jLabel1.setBounds(270, 20, 90, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ΣΣ Apuestas de hoy €€");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel1.add(jLabel2);
        jLabel2.setBounds(0, 60, 900, 40);

        btn_agregar.setBackground(new java.awt.Color(0, 0, 0));
        btn_agregar.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar saldo");
        btn_agregar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        panel1.add(btn_agregar);
        btn_agregar.setBounds(560, 20, 140, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Atl. Nacional");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel1.add(jLabel5);
        jLabel5.setBounds(230, 160, 120, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("U Catolica");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel1.add(jLabel6);
        jLabel6.setBounds(530, 160, 110, 30);

        btn_nacional.setBackground(new java.awt.Color(0, 0, 0));
        btn_nacional.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btn_nacional.setForeground(new java.awt.Color(255, 255, 255));
        btn_nacional.setText("jButton2");
        btn_nacional.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 51)));
        btn_nacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nacionalActionPerformed(evt);
            }
        });
        panel1.add(btn_nacional);
        btn_nacional.setBounds(230, 460, 110, 40);

        btn_catolica.setBackground(new java.awt.Color(0, 0, 0));
        btn_catolica.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btn_catolica.setForeground(new java.awt.Color(255, 255, 255));
        btn_catolica.setText("jButton3");
        btn_catolica.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 204)));
        btn_catolica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_catolicaActionPerformed(evt);
            }
        });
        panel1.add(btn_catolica);
        btn_catolica.setBounds(520, 460, 110, 40);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Atl. Nacional vs U. Catolica de chile");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel1.add(jLabel3);
        jLabel3.setBounds(0, 110, 900, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escudo-logo-atletico-nacional.png"))); // NOI18N
        panel1.add(jLabel4);
        jLabel4.setBounds(160, 200, 220, 250);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Universidad Catolica256x.png"))); // NOI18N
        panel1.add(jLabel7);
        jLabel7.setBounds(450, 200, 240, 250);

        txt_v_apuesta.setBackground(new java.awt.Color(0, 0, 0));
        txt_v_apuesta.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        txt_v_apuesta.setForeground(new java.awt.Color(255, 255, 255));
        txt_v_apuesta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_v_apuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_v_apuestaActionPerformed(evt);
            }
        });
        panel1.add(txt_v_apuesta);
        txt_v_apuesta.setBounds(700, 220, 180, 40);

        txt_pago.setBackground(new java.awt.Color(0, 0, 0));
        txt_pago.setForeground(new java.awt.Color(255, 255, 255));
        panel1.add(txt_pago);
        txt_pago.setBounds(700, 324, 180, 40);

        btn_apostar.setBackground(new java.awt.Color(0, 0, 0));
        btn_apostar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btn_apostar.setForeground(new java.awt.Color(255, 255, 255));
        btn_apostar.setText("Apostar");
        btn_apostar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btn_apostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apostarActionPerformed(evt);
            }
        });
        panel1.add(btn_apostar);
        btn_apostar.setBounds(700, 400, 180, 40);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("¿Cuanto desea apostar?");
        panel1.add(jLabel8);
        jLabel8.setBounds(700, 180, 180, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pago potencial:");
        panel1.add(jLabel9);
        jLabel9.setBounds(700, 290, 180, 20);

        fondo_dos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel1.add(fondo_dos);
        fondo_dos.setBounds(0, 0, 930, 510);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 930, 510));

        titulo.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("ShanderBet - Apuesta más");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/galaxia.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_saldo_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saldo_tActionPerformed
        
        
    }//GEN-LAST:event_txt_saldo_tActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        String a= JOptionPane.showInputDialog(null, "Ingrese saldo");
        int b=Integer.parseInt(a);
        int c= Integer.parseInt(txt_saldo_t.getText());
        int d;
        if (c!=0){
            d=b+c;
            txt_saldo_t.setText(String.valueOf(d));
        }else{
            txt_saldo_t.setText(a);
        }     
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_v_apuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_v_apuestaActionPerformed

        txt_pago.setText("0");
    }//GEN-LAST:event_txt_v_apuestaActionPerformed

    private void btn_nacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nacionalActionPerformed
        double CA= Double.parseDouble(btn_nacional.getText());
        double apuesta= Double.parseDouble(txt_v_apuesta.getText());
        double VG= apuesta*CA;
        txt_pago.setText(String.valueOf(VG));
    }//GEN-LAST:event_btn_nacionalActionPerformed

    private void btn_catolicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_catolicaActionPerformed
        double CA= Double.parseDouble(btn_catolica.getText());
        double apuesta= Double.parseDouble(txt_v_apuesta.getText());
        double VG= apuesta*CA;
        txt_pago.setText(String.valueOf(VG));
    }//GEN-LAST:event_btn_catolicaActionPerformed

    private void btn_apostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apostarActionPerformed
        int apuesta= Integer.parseInt(txt_v_apuesta.getText());
        int saldo_actual=Integer.parseInt(txt_saldo_t.getText());
        
        if(txt_pago.getText().length()==0){
             JOptionPane.showMessageDialog(null, "Has la apuesta por favor");
        }else{
            
            if(apuesta>saldo_actual || apuesta==0){
                JOptionPane.showMessageDialog(null, "Lo lamentamos, no tienes saldo suficiente para apostar");
            }else{
                 int randomNum = (int)(Math.random()*2);
                if(randomNum==0){
                    
                    JOptionPane.showMessageDialog(null, "Perdiste");
              
                     saldo_actual=(saldo_actual-apuesta);
                     txt_saldo_t.setText(String.valueOf(saldo_actual));              
                     
                }else{
                    double pago=Double.parseDouble(txt_pago.getText());
                    int pago_dos=(int)pago;
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    saldo_actual=saldo_actual+pago_dos;
                    txt_saldo_t.setText(String.valueOf(saldo_actual));
                }
                
            }
        }
    }//GEN-LAST:event_btn_apostarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Apuestas_frame frame_anterior= new Apuestas_frame();
       dispose();
       frame_anterior.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apuesta_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apuesta_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apuesta_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apuesta_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apuesta_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_apostar;
    private javax.swing.JButton btn_catolica;
    private javax.swing.JButton btn_nacional;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo_dos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_pago;
    private javax.swing.JTextField txt_saldo_t;
    private javax.swing.JTextField txt_v_apuesta;
    // End of variables declaration//GEN-END:variables

    
}
